name: playground-ci

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ${{ matrix.os }} # runs a test on Ubuntu, Windows and macOS
    strategy:
      matrix:
        os: [ubuntu-latest] # macOS-latest, windows-latest
        node: [14.x]

    name: Node ${{ matrix.node }} - ${{ matrix.os }}

    steps:
      - name: Setup repo
        uses: actions/checkout@v2

      - name: Setup NodeJS ${{ matrix.node }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node }}

      - name: Cache node modules
        uses: actions/cache@v2
        env:
          cache-name: cache-node-modules
        with:
          # npm cache files are stored in `~/.npm` on Linux/macOS
          path: ~/.npm
          key: ${{ matrix.os }}-build-${{ env.cache-name }}-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ matrix.os }}-build-${{ env.cache-name }}-
            ${{ matrix.os }}-build-
            ${{ matrix.os }}-

      - name: Install Dependencies
        run: npm install

      - name: CI Lint
        run: npm run lint

      - name: CI Test
        run: npm run test
